# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

int是整型 float是浮点型 boolean是布尔类型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [6]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
a = np.arange(99)
def sum():
    sum = 0
    for n in a:
        if (n % 2) == 0:
            sum = sum + n+1
        else:
            sum = sum - n-1
    return sum
 
print(sum())




50


1.3  将字符串 s="yoyo" 转换成列表

In [7]:
s = "y o y o"
print(s.split(" "))


['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

1到100，从2号索引开始每三个数排列，取最后十个数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [8]:
class stock:
    def __init__(self,stockName, high, close):
        self.stockName=stockName
        self.high = high
        self.close = close
    def calAmount(self):
        return {self.stockName+'_dif': self.high-self.close}

stockone = stock('one', 15, 7)
print(stockone.calAmount())

stocktwo = stock('two', 66,20)
print(stocktwo.calAmount())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [15]:
import pandas as pd
df=pd.DataFrame(np.random.randn(5,4),columns=['a','b','c','d'])
print(df)
print(df.columns)

          a         b         c         d
0  1.455549  0.466009 -0.384885  1.195023
1  0.743247 -0.951221  0.212173  0.000094
2 -1.681389 -0.293971 -0.125124 -2.044407
3  0.591748 -1.981331 -0.447109  3.046056
4 -0.132352  0.279649  0.440830 -0.667843
Index(['a', 'b', 'c', 'd'], dtype='object')


In [16]:
df.transpose()

0         1         2         3         4
a  1.455549  0.743247 -1.681389  0.591748 -0.132352
b  0.466009 -0.951221 -0.293971 -1.981331  0.279649
c -0.384885  0.212173 -0.125124 -0.447109  0.440830
d  1.195023  0.000094 -2.044407  3.046056 -0.667843

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import talib as ta
import warnings
warnings.filterwarnings('ignore')
stock1 = pd.read_excel('sz50.xlsx',sheetname='600029.XSHG', index_col='datetime')
a=np.array(stock1.close)
print(type(a))
print(ta.EMA(a,10)[-5:])


<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


In [5]:
from datetime import datetime
import pandas as pd
symbol=['600036.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc['2017-03-21':'2017-03-24']
PN = pd.Panel(data_dict)
print(PN)

<class 'numpy.ndarray'>
[ 15.08227205  15.2564044   15.44433088  15.72172526  15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [23]:
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
    data_dict[s] = data.loc['2017-01-03':'2017-11-20']
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

(3, 215, 5)
[[  13.85   13.82   13.83   14.11   14.25   14.39   15.1    15.15   15.22
    14.97   14.89   14.99   14.71   15.07   15.35   16.     16.04   16.29
    16.97   17.05]
 [   8.53    8.56    8.62    8.88    9.25    9.24    9.43    9.25    9.02
     9.15    9.63    9.5     9.9     9.97    9.96    9.49    9.68    9.61
     9.63    9.8 ]
 [ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
   143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
   168.58  169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [26]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
